CC = g++
CFLAGS = -std=c++0x -Wall

all: m1 m2 m3 m4 m5 m6 m7 m8 m9 m10 m11 m12 m13 m14 m15 m16 m17 m18 m19 m20 m21 m22 m23 m24 m25 m26 m27 r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 r12 r13 r14 r15 r16 r17 r18 r19 r20 r21 r22 r23 r24 r25 r26 r27

m1: TCMain.cpp
	$(CC) -o $@ $^ $(CFLAGS) -I../Q4
m2: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q5
m3: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q6
m4: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q7
m5: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q8
m6: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q9
m7: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q10
m8: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q11
m9: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q12
m10: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q13
m11: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q14
m12: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q15
m13: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q16
m14: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q17
m15: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q18
m16: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q19
m17: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q20
m18: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q21
m19: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q22
m20: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q23
m21: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q24
m22: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q25
m23: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q26
m24: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q27
m25: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q28
m26: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q29
m27: 2ndTCMain.cpp
	$(CC) $^ -o $@ $(CFLAGS) -I../Q30

.PHONY: clean r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 r12 r13 r14 r15 r16 r17 r18 r19 r20

clean:
	rm m1 m2 m3 m4 m5 m6 m7 m8 m9 m10 m11 m12 m13 m14 m15 m16 m17 m18 m19 m20 m21 m22 m23 m24 m25 m26 m27

r1:
	./m1
r2:
	./m2
r3:
	./m3
r4:
	./m4
r5:
	./m5
r6:
	./m6
r7:
	./m7
r8:
	./m8
r9:
	./m9
r10:
	./m10
r11:
	./m11
r12:
	./m12
r13:
	./m13
r14:
	./m14
r15:
	./m15
r16:
	./m16
r17:
	./m17
r18:
	./m18
r19:
	./m19
r20:
	./m20
r21:
	./m21
r22:
	./m22
r23:
	./m23
r24:
	./m24
r25:
	./m25
r26:
	./m26
r27:
	./m27
